name: Terraform
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  # terraform-plan:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout 
  #       uses: actions/checkout@v4
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3
  #     - name: Terraform fmt
  #       id: fmt
  #       run: terraform fmt -check
  #     - name: Terraform Init
  #       id: init
  #       run: terraform init
  #     - name: Terraform Validate
  #       id: validate
  #       run: terraform validate -no-color
  #     - name: Terraform plan
  #       id: validate
  #       run: terraform validate -no-color
  terraform-apply:
    if: github.ref == 'refs/heads/add-workflow'
    runs-on: ubuntu-latest
    steps:
      - name: DUMP GITHUB
        env: 
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: echo "$GITHUB_CONTEXT"
    